<?php

namespace App\Http\Controllers\Data;

use Illuminate\Http\Request;
use App\Models\Data\SysMessageInfo;
use DB;
use App\Http\Controllers\Frame\AppDataController;

class SysMessageInfoController extends AppDataController {

    public function __construct(Request $request, SysMessageInfo $model) {
        parent::__construct($request, $model);
        $this->middleware('auth');
    }

    protected function get_where($request, $dataset) {
        $where = parent::get_where($request, $dataset);
        $where = $this->get_default_where($request, $where);
        $where['eq']['role_id'] = $request->__user->role_id;
        return $where;
    }

    protected function get_fields($request, $dataset) {
        return ['id' , 'content' , 'url'];
    }

    public function index(Request $request) {
        $request['status'] = 0;
        return parent::index($request); // TODO: Change the autogenerated stub
    }

}
